[package]
name = "termcineua"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
async-recursion = "1.1.0"
crossterm = "0.27.0"
reqwest = "0.12.3"
serde = "1.0.197"
serde_json = "1.0.115"
tempdir = "0.3.7"
thirtyfour = "0.31.0"
tokio = { version = "1.37.0", features = ["full"] }
